name: check_format

on:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install clang-format
        run: |
            sudo apt install -y clang-format
            clang-format --version

      - name: check format
        run: make check_format
